### PR TITLE
feat: add server level command and merge

### PR DESCRIPTION
**Pull request by sheny1xuan**
Signed-off-by: stonex <1479765922@qq.com>

+ When location and server has different command, use location first.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@EmperorYP7 please review

**Comment by hsluoyz** [comment]
@EmperorYP7 please review

**Review by EmperorYP7 — APPROVED** [review]
LGTM

**Comment by EmperorYP7** [comment]
@sheny1xuan Can we set up a CI for this project?

**Comment by sheny1xuan** [comment]
> Can we set up a CI for this project?

Good point, I will try it latter.

**Comment by EmperorYP7** [comment]
@sheny1xuan

**Pull request merged**
